[WIP] Partial/incremental decompression of clusters
openzim/libzim pull request #411
Opened 2020-08-28 15:35 UTC by veloman-yunkan

When ready this PR will close #394 and #395

2020-08-31 08:10 UTC, mgautierfr commented
That is a big change (I've just quickly read it, not made a review). But as said in https://github.com/openzim/libzim/issues/395#issuecomment-671435908, it would have been nice to have some measurements to know where we are going instead of doing such big change for potentially nothing (or worst).


Can you explain the global strategy for this PR ?

2020-08-31 08:49 UTC, veloman-yunkan commented
This PR is only about partial/incremental decompression (it doesn't include caching on article/item level, though, of course, advances in that direction). As a result of this change clusters are decompressed lazily. When `i`'th blob is first accessed, the cluster is decompressed up to and including blob `#i`. If blob `#(i+j)` is later accessed (before that cluster is evicted from the cache), decompression continues from the state at which it was suspended. In a random access scenario with a limited size of the cluster cache (and assuming that the articles/items are not grouped into clusters in a smart way), this approach should result on average in about 2x speed-up of cluster decompression (at least, in terms of latency of blob access) as well as 2x reduction in memory usage.

Some minor sources of slowdown are the following:

1. Cluster is now a polymorphic object (non-compressed and compressed clusters being two sub-classes)
2. Access to blobs is guarded with a mutex
3. Some other implementation-specific shortcuts that can be eliminated.

I am confident that the potential performance improvement will greatly exceed the slowdown, that's why I didn't start with measurement.

2020-08-31 09:02 UTC, mgautierfr commented
> When i'th blob is first accessed, the cluster is decompressed up to and including blob #i. If blob #(i+j) is later accessed (before that cluster is evicted from the cache), decompression continues from the state at which it was suspended

How do you handle the need of more memory as you decompressing more data while keeping existing pointer valid ?

2020-08-31 09:29 UTC, veloman-yunkan commented
@mgautierfr 

Blobs of *known size* are read from a data stream that is decompressed on the fly: https://github.com/openzim/libzim/blob/a22773c4ec08a0ff4e82b6b29b76e27eb440b51b/src/cluster.cpp#L278-L283

`DecodedDataStream`, which is in charge of the on-the-fly decompression, easily decompresses the requested number of bytes (look at the function `readImpl()` first)

https://github.com/openzim/libzim/blob/a22773c4ec08a0ff4e82b6b29b76e27eb440b51b/src/decodeddatastream.h#L46-L78

into a buffer that is created for it by its superclass: https://github.com/openzim/libzim/blob/a22773c4ec08a0ff4e82b6b29b76e27eb440b51b/src/idatastream.cpp#L30-L36

2020-09-03 16:06 UTC, mgautierfr requested changes
This is a interesting PR. There are some few things I like and some other I don't :)

I mainly disagree with the new code architecture this change introduces.

Let's me explain first the global architecture of the classes of the libzim.
- `Buffer` represents a memory region. There are several kind of buffers as the memory region can be handled differently (not handled, simply deleted at destruction or mmap backed)
- `Reader` is a interface to read data. It can read data directly from a (potentially split) file (`FileReader`) or from a memory zone (`BufferReader`).
- Other classes (`Dirent`, `FileImpl` and `Cluster`) use a reader to get data. They are about interpret the data they read (the logic) and not how the data is stored/read (implementation). [1]
- `FileImpl` is the smart part that create appropriate `Reader`/`Buffer` depending of the context.
- `Blob` is the end of the chain. It the (size aware) data returned to the user. It represent a memory zone (as a `Buffer`). Technically it could be replaced by a `Buffer` but a `Buffer` is something internal to the libzim and `Blob` is public (and `Blob` was here long time before `Buffer` and I didn't what to break the api when I introduced `Buffer`).

In our case, this architecture allow :
- Split the reading of the data (`Reader`/`Buffer`) from its interpretation (`Cluster`/`Dirent`) using a interface (`Reader`) between the both. [1]
- `FileImpl` to create the "best" reader to read some cluster data (if not compressed: FileReader. If compressed: BufferReader on a decompressed memory region)
- `Cluster` don't have to care about how data is stored. It only care about reading the data and interpret it.

What missing is a way to have lazy decompression. This is mostly because the decompression algorithm is not associated with a reader but it is just a way to create a buffer. So `FileImpl` have to decompress the whole cluster data to pass a `Reader` to `Cluster`.

What you do in this PR complicate a lot the global architecture :
- You split the `Cluster` implementation in two and use different algorithm and storage depending of how the data is read. You break the separation between two different problem.
- Create new kind of itermediate class (`IDataStream`, `IDataStream::Blob`)
- Add somehow complex relation between `zim::Blob`, `IDataStream::Blob` and `Buffer`.

---

I don't think we need a dataStream at all. We "simply" need to create a `DecompressReader` that lazy decompress the data just when we need(read) it.
The cluster would have to be change a bit. It would have to store the buffer of the already blob and be sure that buffer inferior to `idx` has been read when getting blob `idx`.

Here is a pseudo code of the `DecompressReader` and the change to made on `Cluster`.

```cpp
class DecompressReader : public Reader
{
  void read(char* dest, offset_t offset, zsize_t size) const {
    // The following code should not used as we are smart on cluster side.
    // But we need it to be a fully functional as a reader.
    if (last_read_offset > offset) {
       last_read_offset = 0;
    }
    // decompress from last_read_offset to offset (and drop decompressed memory);
    decompress(offset-last_read_offset, nullptr);
    
    // Here is the useful decompress
    decompress(size, dest);
    last_read_offset = offset+size;
  }

  void decompress(zsize_t size, char* dest) {
    //reuse the code of the DecodedDataStream
  }

  std::shared_ptr<const Buffer> FileReader::get_buffer(offset_t offset, zsize_t size) const {
	auto ret_buffer = std::make_shared<MemoryBuffer>(size);
    read(ret_buffer->buf(), offset, size);
    return ret_buffer;
  }

  Buffer/*or Reader*/ compresseddata;
  compression_stream  stream;
  offset_t     last_read_offset;
};


class Cluster //updated code
{
  Blob getBlob(blob_index_t n) const
  {
    auto nb_read_buffers = already_read_buffers.size();
    for (auto i=nb_read_buffers; i<=n; i++) {
      // If cluster is not compressed, reader is a `BufferReader` and the create buffer is a sub buffer without memory copy
      // If cluster is compressed, reader is a `DecompressReader` and the create buffer is a "just in time" allocated and decompressed buffer.
      auto buffer = reader->get_buffer(startOffset+offsets[blob_index_type(i)], getBlobSize(i));
      already_read_buffers.push_back(buffer);
    }
    return Blob(already_read_buffers[n]);
  }
  std::vector<std::shared_ptr<const Buffer>> already_read_buffers;
}

---

[1] Yes, `Dirent` uses a `Buffer` and not a `Reader`. But this is because I haven't made thing correctly. We should change this to make the `Dirent` use a `Reader`, potentially creating a buffered reader (not to be confused with `BufferReader`) to avoid too many syscall when reading each dirent's fields. Directly using a `Buffer` is somehow a wrong implementation of a lazy developer (me) than a design choice.

2020-09-03 16:12 UTC, veloman-yunkan commented on test/readerdatastreamwrapper.cpp
> +  const Reader* readerPtr = &bufReader;
This validates that `ReaderDataStreamWrapper` constructor takes a `Reader` pointer.

2020-09-03 16:19 UTC, veloman-yunkan commented on src/readerdatastreamwrapper.h
> +  explicit ReaderDataStreamWrapper(const zim::Reader* reader)
That's a matter of convention - a function taking a pointer advertises that it is going to keep that address and use it later, whereas a function taking a reference should not use its argument address after it returns.  Note that the signature of the `ReaderDataStreamWrapper` constructor is obsoleted by a later commit (see https://github.com/openzim/libzim/pull/411/commits/757cd27656dd04d35b7907d4b76860a0f9470a2e#diff-bd936cc7a08e7557d6f67d74e64741f0L33-R33)

2020-09-03 16:20 UTC, veloman-yunkan commented on src/cluster.h
> +      virtual bool isCompressed() const override;
I prefer to define virtual functions of non template classes in the .cpp file to facilitate the compiler's and linker's jobs (and speed up the build time).

2020-09-03 16:28 UTC, veloman-yunkan commented on src/decodeddatastream.h
> +  enum { CHUNK_SIZE = 1024 };
Macros are not protected by scope, so I never `#define` constants. When I don't care about the type of an integral constant (only about its value) I use `enum`, which is less verbose - the alternative in this case would be

```c++
static const int CHUNK_SIZE = 1024;
```

2020-09-03 16:33 UTC, veloman-yunkan commented on test/decodeddatastream.cpp
> +  const std::string compData = compress<CompressionInfo>(s*N);
Good catch!

2020-09-03 16:39 UTC, veloman-yunkan commented on src/bufdatastream.h
> +class BufDataStream : public IDataStream
You are right. I thought it was used in an intermediate state but it only enables unit-testing `DecodedDataStream`.

2020-09-03 17:08 UTC, veloman-yunkan commented
> Let's me explain first the global architecture of the classes of the libzim.
> 
>     * `Buffer` represents a memory region. There are several kind of buffers as the memory region can be handled differently (not handled, simply deleted at destruction or mmap backed)

The fact that `zim::Buffer` always represents a real memory region (rather than emulates representing a memory region, while possibly serving data from a remote resource or otherwise producing it on demand), undermines the role of all polymorphic `Buffer` classes. The same can be achieved with a class very similar (if not identical) to `IDataStream::Blob` and a family of factory functions:

```c++
Buffer makeMemoryBuffer(size_t size)
{
  return Buffer(std::shared_ptr<const char>(new char[size], std::default_delete<char[]>()), size);
}

Buffer makeMemoryViewBuffer(const char* start, size_t size)
{
  return Buffer(std::shared_ptr<const char>(start, NoDelete()), size);
}

Buffer makeMmapBuffer(const char* start, size_t size)
{
  // pseudocode
  Mmapping mmapping(start, size);
  return Buffer(std::shared_ptr<const char>(start, mmapping.getUnmmapper()), size);
}
```

That's why I think that `IDataStream::Blob` is a step in the right direction, allowing to get rid of `Buffer` and its sub-classes (after we replace zim::Blob with such an implementation).

2020-09-03 17:12 UTC, veloman-yunkan commented
> What you do in this PR complicate a lot the global architecture :
> 
>     * You split the `Cluster` implementation in two and use different algorithm and storage depending of how the data is read. You break the separation between two different problem.
> 
>     * Create new kind of itermediate class (`IDataStream`, `IDataStream::Blob`)
> 
>     * Add somehow complex relation between `zim::Blob`, `IDataStream::Blob` and `Buffer`.

You are right that the new code adds some complexity. A far reaching intent is to arrive at a simpler architecture as outlined in the previous comment.

2020-09-03 17:25 UTC, veloman-yunkan commented
> I don't think we need a dataStream at all. We "simply" need to create a `DecompressReader` that lazy decompress the data just when we need(read) it.
> The cluster would have to be change a bit. It would have to store the buffer of the already blob and be sure that buffer inferior to `idx` has been read when getting blob `idx`.
> 
> Here is a pseudo code of the `DecompressReader` and the change to made on `Cluster`.
> 
> ```c++
> class DecompressReader : public Reader
> {
>   void read(char* dest, offset_t offset, zsize_t size) const {
>     // The following code should not used as we are smart on cluster side.
>     // But we need it to be a fully functional as a reader.
>     if (last_read_offset > offset) {
>        last_read_offset = 0;
>     }
>     // decompress from last_read_offset to offset (and drop decompressed memory);
>     decompress(offset-last_read_offset, nullptr);
>     
>     // Here is the useful decompress
>     decompress(size, dest);
>     last_read_offset = offset+size;
>   }
> ```

Yes, that will work. But it achieves the result by using a more complex tool (the random access `Reader`) in a situation where a simpler tool  (a sequential reader modeled in this PR by `IDataStream`) will do. Of course there is the problematic tradeoff between having a single general purpose tool, or having multiple specialized tools, which doesn't have an easy answer. My point of view is that sequential scanning of data has proven its usefulness in a number of areas, and we better have and utilize that abstraction in our code.

2020-09-03 18:52 UTC, veloman-yunkan commented
On one hand you write 

> What you do in this PR complicate a lot the global architecture :
> 
>  * You split the `Cluster` implementation in two and use different algorithm and storage depending of how the data is read. You break the separation between two different problem.

On the other hand you propose
> ```c++
> class Cluster //updated code
> {
>   Blob getBlob(blob_index_t n) const
>   {
>     auto nb_read_buffers = already_read_buffers.size();
>     for (auto i=nb_read_buffers; i<=n; i++) {
>       // If cluster is not compressed, reader is a `BufferReader` and the create buffer is a sub buffer without memory copy
>       // If cluster is compressed, reader is a `DecompressReader` and the create buffer is a "just in time" allocated and decompressed buffer.
>       auto buffer = reader->get_buffer(startOffset+offsets[blob_index_type(i)], getBlobSize(i));
>       already_read_buffers.push_back(buffer);
>     }
>     return Blob(already_read_buffers[n]);
>   }
>   std::vector<std::shared_ptr<const Buffer>> already_read_buffers;
> }
> ```

which is sub-optimal for non-compressed clusters. The distinction between non-compressed and compressed clusters (if we thrive for the most optimal solution in each case) is that of between random and sequential access, which has no solution other than treat them differently.

2020-09-05 13:00 UTC, veloman-yunkan commented on test/decodeddatastream.cpp
> +  const std::string compData = compress<CompressionInfo>(s*N);
This is now covered by `DecodedDataStreamTest.largeCompressedData`

2020-09-05 13:08 UTC, veloman-yunkan commented on src/idatastream.h
> +  };
My intention is to promote `IDataStream::Blob` to `zim::Blob`, so eventually we will use `zim::Blob` here :wink:

This version of a blob implementation has several advantages over the current version of `zim::Blob`

1. It is a little more lightweight
2. and still can replace, after minor enhancements, both `zim::Blob` and `zim::Buffer`

2020-09-05 13:11 UTC, veloman-yunkan commented on src/bufdatastream.h
> +  size_t size_;
I have wicked plans of getting rid of `zim::Buffer`

2020-09-05 13:16 UTC, veloman-yunkan commented on src/cluster.cpp
> +class IDSBlobBuffer : public Buffer
I guess there is some misunderstanding here. This is a temporary helper class used to translate wrap `IDataStream::Blob` in a `zim::Blob`.

This is probably the ugliest part of the new code that will be eliminated when `IDataStream::Blob` takes over `zim::Blob`

2020-09-05 13:17 UTC, veloman-yunkan commented on src/cluster.cpp
> +  return Blob(std::make_shared<IDSBlobBuffer>(blob, offset, size));
The data is already loaded at this point (and blob points to it).

2020-09-05 16:19 UTC, veloman-yunkan commented
Added benchmarking data in the [description of this PR](https://github.com/openzim/libzim/pull/411#issue-475476415).

2020-09-07 08:53 UTC, mgautierfr commented on src/bufdatastream.h
> +  size_t size_;
Please stop wicked plans :) Let's talk together before.

2020-09-07 09:12 UTC, mgautierfr commented
> The fact that zim::Buffer always represents a real memory region (rather than emulates representing a memory region, while possibly serving data from a remote resource or otherwise producing it on demand), undermines the role of all polymorphic Buffer classes.

Having something to read data, possibly served from a remote resource is the job of `Reader`.
It is not a flaw of polymorphic design if a class designed as A cannot be B.

> A far reaching intent is to arrive at a simpler architecture as outlined in the previous comment (as well as noted in #402 (comment))

Please talk with me before making plan to libzim and implementing things.

> Yes, that will work. But it achieves the result by using a more complex tool (the random access Reader) in a situation where a simpler tool (a sequential reader modeled in this PR by IDataStream) will do.

I'm not sure a sequential reader is simpler. But anyway, we would end with two tools instead of one. And the global situation would definitively not be simpler.

> My point of view is that sequential scanning of data has proven its usefulness in a number of areas, and we better have and utilize that abstraction in our code.

How ? The only usecase we have is for decompression stream.
We are not designing a generic "reading system". We are creating a sub-system for libzim and libzim only.

> which is sub-optimal for non-compressed clusters.

How it is sub-optimal ? Uncompressed clusters still have no memory copy, no big data allocation (not more than before). The only things that are created/copied are few shared_ptr. And this is a price I totally accept for a simple design.

2020-09-07 09:20 UTC, mgautierfr commented
One another important point is that this should be threadsafe.
This is the case with the current code as the compression is made in one step and then we are just reading const data.
But here we must protect all read access as we may decompress data.

2020-09-23 17:24 UTC, kelson42 commented
Superseeded by #421

2020-09-23 17:24 UTC, closed without merging