Create a validate free function in zim ns
openzim/libzim pull request #425
Opened 2020-09-23 15:41 UTC by MiguelRocha

This PR introduces the first step for libzim validation. It adds a free function that does basic zim file validations. This function can be called by an external tool (example zimcheck).

More info: https://github.com/openzim/libzim/issues/359

2020-09-30 10:49 UTC, kelson42 commented
@MiguelRocha Any news here?

2020-10-18 13:29 UTC, MiguelRocha commented
@mgautierfr can you please review?

2020-10-20 14:38 UTC, mgautierfr requested changes

2020-10-20 14:38 UTC, mgautierfr commented on src/file.cpp
> +              auto article = f.getArticle(i);
Getting a article using its index will use the `UrlPtrList` to get the article. So the article should indeed be url sorted (or url increasing as index is increasing).

But it say nothing about the title. Even on a correct zim file, the title order may differ from the url order.
This is way we have the TitlePtrList.

- `Dirent.atOffset(UrlPtrList[idx]).fullurl` should be increasing when idx is increasing
- `Dirent.atOffset(UrlPtrList[TitlePtrList[idx]]).fulltitle` should be increasing when idx is increasing.

(`atOffset` and `fulltitle` don't exist but you got the idea :) )

2020-11-10 10:33 UTC, veloman-yunkan commented
This version covers the first step from https://github.com/openzim/libzim/issues/359#issuecomment-686373390:

> The fist step is to create this function and do some easy checks in it :
> 
> - Magic number in zim header is valid.
> - Offsets in zim header are valid (< zim size).
> - Offsets in UrlPtrList and ClusterPtrList are valid
> - Index in TitlePtrList are valid (< articleNumber)

All checks are covered by a new unit-test `ZimFile.validate`. ZIM files used by that unit-test must be generated using the `test/data/create_test_zimfiles` script (they are version controlled and must be be updated and committed whenever the source data or the said script changes).

2020-11-10 16:03 UTC, mgautierfr approved these changes
This PR version doesn't test the dirent content (while previous version does).
It means that it doesn't test that mimetype is correct or that url and title are correctly sorted.

However, I'm good with this PR. It introduce nice validity structure we can extend with mimetype/url/title check later.

2020-11-11 14:32 UTC, kelson42 commented
@veloman-yunkan @mgautierfr What is left here to do?

2020-11-11 14:37 UTC, mgautierfr commented
> What is left here to do?

Technically nothing. The code is good.
Functionally, there is no check that MimeTypes are valid or UrlPtrList and TitlePtrList are correctly sorted.

I propose to merge this PR as it is and add missing tests in another PR.

2020-11-11 14:40 UTC, merged