Remove test data from repository and use data from zim-testing-suite.
openzim/libzim pull request #538
Opened 2021-04-20 14:43 UTC by mgautierfr

This PR remove the data from the repository and download the data from zim-testing-suite.

It should be considered as a preparatory work of https://github.com/openzim/libzim/pull/535.
It replace https://github.com/openzim/libzim/pull/531 answering comments addressed:
- Put the test data version somewhere in the code to know which data to use with which version of the code.
- Simplify the downloading of the data (now repository contain a scrip to do it and can be run through meson).
- User can download the data and use the downloaded data.

@legoktm On packaging side, you can use the provided script to download the data or make the archive a second source and just configure meson correctly.

For now, this PR works only if `test_data_dir` option is not used (tests look in `test/data` directory in build dir).
This PR must be considered with #535 where test are using data pointed by the env var.
The two PR will be merge together to avoid to add the new zim files to the repository. But I've created a separated PR to concentrate on the download process as we already agreed on the new tests themselves.

2021-04-20 19:35 UTC, veloman-yunkan requested changes
README.md must be updated

2021-04-21 09:24 UTC, mgautierfr commented
> README.md must be updated

Done.

2021-04-21 13:41 UTC, veloman-yunkan requested changes

2021-04-21 13:41 UTC, veloman-yunkan commented on README.md
> +- Use the script [download_test_data.py](scripts/download_test_data.py) which will download and extra the data for you.
extra → extract

2021-04-21 13:41 UTC, veloman-yunkan commented on README.md
> +By default, meson will use a internal directory in you build directory.
you → your

2021-04-21 13:41 UTC, veloman-yunkan commented on README.md
> +The unit test need testing zim files.
Change this sentence to "ZIM files needed by unit-tests are not included in this repository. You must tell meson where the test data is located."

2021-04-21 15:22 UTC, veloman-yunkan approved these changes

2021-04-21 15:36 UTC, mgautierfr commented
@legoktm Is it ok for you ?
I don't know how to patch `debian/rules` to add the `ninja download_test_data` during the build.
(I'm not even sure we should as the build step is probably offline.)

2021-04-23 07:11 UTC, legoktm commented
> @legoktm Is it ok for you ?

As you had suggested in https://github.com/openzim/libzim/pull/531#issuecomment-819351398, can we have an environment variable that causes it to skip these tests? That can be set in debian/rules and then fixing the packaging no longer blocks you.

> I don't know how to patch `debian/rules` to add the `ninja download_test_data` during the build.
> (I'm not even sure we should as the build step is probably offline.)

Yes, building the Debian package shouldn't require any Internet dependencies. We (I really) should add the packaging configuration to zim-testing-suite so it's in our PPA and libzim can depend on it like a normal apt dependency. I can start working on that over the weekend.

2021-04-26 08:41 UTC, kelson42 commented
@legoktm Any news about a fix of the deb package CI?

2021-04-27 12:47 UTC, mgautierfr commented
@legoktm last commit add a option to deactivate tests using external test data.

We need to pass the option `-Dtest_data_dir=none` to meson.
If you tell we how to pass this option to meson in the debian/rules I can do the patch myself and we will be good.

2021-04-27 21:55 UTC, legoktm commented
> @legoktm last commit add a option to deactivate tests using external test data.
> 
> We need to pass the option `-Dtest_data_dir=none` to meson.
> If you tell we how to pass this option to meson in the debian/rules I can do the patch myself and we will be good.

I had to look it up myself :) pushed the fix, which also makes it obvious how to add more config flags in the future.

2021-04-27 21:55 UTC, legoktm approved these changes

2021-04-28 05:57 UTC, kelson42 commented
There is still two codefactor issues.

2021-04-28 07:59 UTC, mgautierfr commented
> There is still two codefactor issues.

I consider them as two false positives.

2021-04-28 12:56 UTC, merged