Add unit test for search iterator
openzim/libzim pull request #547
Opened 2021-04-27 20:11 UTC by maneeshpm

Fixes #546 

Changes contained this PR:
- Move helper code `TempZimArchive` & `TestItem` to tools for better usability.
- Add some unit tests for the search iterator.

2021-04-28 15:13 UTC, maneeshpm commented
@mgautierfr why is the build failing only on some systems?

2021-04-29 06:44 UTC, kelson42 commented
@maneeshpm Thx for this PR, we have reached now 80% of code coverage :)

2021-04-30 19:38 UTC, kelson42 commented
@maneeshpm please rebase on master

2021-05-01 05:00 UTC, maneeshpm commented
@kelson42  done.

2021-05-04 12:52 UTC, mgautierfr requested changes
It would be good to test more than just `get_title` method on the iterator.
But we can go without it for now and add it later, this is a improvement anyway.

2021-05-04 12:52 UTC, mgautierfr commented on test/meson.build
> +    'search_iterator'
This test must be compiled only if `xapian_dep` is found.

2021-05-05 08:03 UTC, mgautierfr commented
Please rebase-fixup the PR and we are good.

2021-05-05 13:14 UTC, maneeshpm commented
@mgautierfr Done!

2021-05-05 13:41 UTC, mgautierfr approved these changes

2021-05-05 13:41 UTC, merged