Fix documentation of getResults
openzim/libzim pull request #597
Opened 2021-07-30 16:43 UTC by maneeshpm

Fixes #596 

I propose we should follow the same convention as used by Xapian for consistency. That is, rather than keeping the second argument of `Search::getResults(start, end)` as `end` of range, we should use `maxResults` as the second argument. This way:
`getResult(start, maxResults)` will return results in the range `(start, start + maxResults)`

This makes use of API much easier and will require just a documentation fix. We need to fix the rest of the projects accordingly(even though they still work and won't break after this change) for which issues are being created.

2021-07-31 08:54 UTC, kelson42 approved these changes

2021-07-31 08:55 UTC, kelson42 commented
@maneeshpm LGTM

2021-08-03 08:56 UTC, mgautierfr requested changes
Wow! It seems that it is not a simple documentation fix.

https://xapian.org/docs/apidoc/html/classXapian_1_1Enquire.html#a1f2e35f79bc731bebfbdaceda17b9892 indeed takes a maxResults, not a end.
So the previous code was buggy. We must check in all our user code how this is used. And add unit test getting range of results in the middle of the search to test this.

2021-08-03 10:09 UTC, maneeshpm commented
@mgautierfr Another possible solution is, instead of changing any of our existing user code, we modify `getResult(start, end)`. We can first find `maxItems` as `end - start` and use this in `get_mset`. We might have to check if the `maxItems` calculated like this is valid or not and throw an error accordingly. This would help to keep the issue confined within libzim. But we would have this inconsistency with Xapian get_mset which would have to be documented explicitly.

2021-08-03 10:16 UTC, kelson42 commented
@maneeshpm I'm not in favour of generating an exception here for that. Your fix seems proper to me, it just has to be tested properly. Keep in mind the libzim should be easy to use.

2021-08-03 10:19 UTC, maneeshpm commented
@kelson42 I agree. We can go ahead and create corresponding tickets to "Check proper usage of getResults" in the rest of our projects and check them one by one.

2021-08-03 10:23 UTC, kelson42 commented
@maneeshpm Usually I'm not in favour to create test dedicated ticket excpet if there is a really good reason. Creating automated tests is part of the feature/bugfix development and multiplicatying tickets without reasons just makes things uselessly more complex. IMO it should be done in this PR, or do you see a really good reason to not do it now?

2021-08-03 10:28 UTC, maneeshpm commented
@kelson42 I meant in the rest of our projects like kiwix-destop where this might be causing an issue, but we will have to check. I will add a test for libzim in this pr itself.

2021-08-03 10:38 UTC, kelson42 commented
@maneeshpm OK, I understand better. Once the PR is completed, would be great if you could check that the following repository are not impacted by a wrong assumption about  `end/maxResults`:
* openzim/python-libzim
* openzim/zim-tools (zimsearch)
* kiwix/libkiwix
* kiwix/kiwix-tools (kiiwx-serve)
* kiwix/kiwix-desktop
* kiwix/java-libkiwix

And if you see something just open a ticket then.

2021-08-04 07:43 UTC, kelson42 commented
@mgautierfr Can we merge this?

2021-08-04 08:35 UTC, mgautierfr approved these changes

2021-08-04 08:35 UTC, merged