Add basic documentation.
openzim/libzim pull request #611
Opened 2021-08-19 08:59 UTC by mgautierfr

- Basic usage. Mainly taken from https://wiki.openzim.org/wiki/Libzim
  with (a lot of) adaptation.
- Transition guide from libzim6 to libzim7.

This is a basic documentation and doesn't cover all features of libzim.

Fix #608

2021-08-20 18:05 UTC, maneeshpm requested changes
Just some minor typo errors and a few suggestions. Good one!

2021-08-20 18:05 UTC, maneeshpm commented on docs/usage.rst
> +It has actually a reference to a implementation, so that copies of the class just references the same file.
reference to *an* implementation

2021-08-21 18:39 UTC, rgaudin approved these changes
Great addition

2021-08-22 13:30 UTC, kelson42 approved these changes

2021-08-22 17:38 UTC, veloman-yunkan approved these changes
Fixing typos & grammar and improving some pieces of the (new) documentation will unnecessarily delay merging this PR. It is a good start, we can merge it as is and then have someone refine it.

2021-08-23 05:23 UTC, maneeshpm approved these changes
I agree with @veloman-yunkan, we can refine it later.

2021-08-23 08:34 UTC, mgautierfr commented on docs/6to7.rst
> + .. code-block:: c++
I've removed all includes for consistency.

2021-08-23 08:34 UTC, mgautierfr commented on docs/6to7.rst
> +    #include <zim/archive.h>
I've removed all includes for consistency.

2021-08-23 08:41 UTC, mgautierfr commented
Rebased on master and I've fixed the few typos.
Feel free to create PR to improve the documentation.

Deb packaging CI is failing but nothing related to this PR. I'm merging.

2021-08-23 08:41 UTC, merged