Be more tolerant to threads scheduling in unit tests.
openzim/libzim pull request #748
Opened 2022-11-22 13:29 UTC by mgautierfr

Wait for few (milli)seconds is not enough.
Thread may run sooner or later than expected.

New testiing checks that the following appears **in order**:
- One or several calls without throwing an error
- One (and only) call throwing an `AsyncError`
- Following calls always throwing a CreatorStateError.
- Last call always throws a exception.

Fix #747

2022-11-23 08:13 UTC, veloman-yunkan reviewed
While reviewing this PR I figured out something that should have been proposed in #496 - shouldn't there be a test for a flow with async errors where `finishZimCreation()` isn't called at the end, so that we can make sure that the `Creator` destructor doesn't rely on that method for clean-up of any effects caused by intercepted asynchronous errors?

2022-11-23 08:13 UTC, veloman-yunkan commented on test/error_in_creator.cpp
> +#define CHECK_ASYNC_EXCEPT(CALL, MUST_FAIL) \
It is possible to get rid of the `MUST_FAIL` parameter as follows:

```c++
// finishZimCreation() always waits for workers, so we MUST have an exception.
const bool MUST_FAIL = std::string(#CALL).find("finishZimCreation") != std::string::npos;
```

2022-11-23 14:36 UTC, mgautierfr commented on test/error_in_creator.cpp
> +  bool async_error_thrown = false;
I tend to think of TestSuite (as `FaultyDelayedItemErrorTest`) as provider of fixture (or just a "implementation detail" necessary structure).

`async_error_throw` is not a fixture but a variable describing the context of the running test. It is better to have it declared in the test itself.

2022-11-23 16:03 UTC, veloman-yunkan requested changes
Please fix the commit history during rebase&fixup and we are good.

2022-11-23 16:03 UTC, veloman-yunkan commented on test/error_in_creator.cpp
> +}
This better be placed in a commit of its own.

2022-11-23 17:11 UTC, veloman-yunkan approved these changes
There is one tiny issue that can be fixed before merging without an additional review.

2022-11-30 10:31 UTC, kelson42 commented
Good to merge now I guess?

2022-11-30 10:33 UTC, merged