Add a unit test showing bug with CJK indexing.
openzim/libzim pull request #806
Opened 2023-06-07 13:23 UTC by mgautierfr

2023-06-07 14:34 UTC, kelson42 commented
@mgautierfr Can you please provide an index size benchmark?

2023-06-08 13:19 UTC, veloman-yunkan requested changes
Is the commit containing the fix final? If yes, why does it have [WIP] in its title?

2023-06-08 13:19 UTC, veloman-yunkan commented on test/suggestion.cpp
> +TEST(Suggestion, CZK) {
CZK -> CJK

2023-06-08 13:19 UTC, veloman-yunkan commented on test/search.cpp
> +    // So `平方` must also found `平方根`
found -> find

2023-06-08 13:41 UTC, mgautierfr commented
> Also, do you have an explanation for why the codecov/patch flow has failed?

For a unknown reason (maybe the `assert` at the beginning of function ?), codecov thinks the line are partially tested.
Maybe it is not totally counted as tested and, as we add new lines, the coverage decrease.

2023-06-08 14:29 UTC, veloman-yunkan approved these changes
Don't merge without squashing the fixup commit.
*Don't merge without squashing the fixup commit.*
**Don't merge without squashing the fixup commit.**
***Don't merge without squashing the fixup commit.***

2023-06-08 15:00 UTC, merged