Add some unittest on get_buffer
openzim/libzim pull request #889
Opened 2024-05-30 15:11 UTC by mgautierfr

This Pr was initially to fix #886. But it appears it was not a bug on our side.

However, it is better testing and it reveals some bug on Windows side.

2024-05-30 18:30 UTC, kelson42 commented
Where is rhe codecov, it seems it has vanished!

2024-05-30 18:33 UTC, rgaudin commented
I think it doesn't run on drafts

2024-06-11 09:24 UTC, veloman-yunkan requested changes

2024-06-11 09:24 UTC, veloman-yunkan commented on src/fs_unix.cpp
> +    if (size_read == 0) {
This is comment on the commit message:

- excepts → expects
- is → if

2024-06-17 09:04 UTC, mgautierfr commented on src/fs_windows.cpp
> +  if (full_size_read != size.v) {
Indeed. `full_size_read` removed.

2024-06-17 09:10 UTC, mgautierfr commented on src/fs_windows.cpp
> +	if (size_read == 0) {
From `ReadFile` function, it is technically possible than `size_read != batch_to_read`. If we reach the end of file or (at least on linux, don't known on windows) if we have been interrupted by a signal.

The eof should not happen as we have check validity of the read before.

But I prefer to keep it. If it appear it is really something wrong (unexpected eof), we would have a step more in the loop before throwing a error (and mostly stopping the program).

2024-06-17 09:10 UTC, mgautierfr commented on src/fs_windows.cpp
> +	auto batch_to_read = std::min(size_to_read, (size_type)4*1024*1024);
Indeed. Done.

2024-06-17 12:01 UTC, veloman-yunkan reviewed
Please rebase and fix up. I am almost certain that then it will LGTM.

2024-06-17 12:27 UTC, veloman-yunkan reviewed
Looks good to me but not to my more picky self :)

Please merge after addressing the two concerns with the commit history

2024-06-17 12:27 UTC, veloman-yunkan commented on src/reader.h
> +    }
It would be nice if the commit message is updated

2024-06-17 12:27 UTC, veloman-yunkan commented on src/buffer_reader.h
> +    offset_t offset() const override;
This commit better be moved right after the one introducing `Reader::readImpl()`

2024-06-17 12:48 UTC, mgautierfr commented
> Looks good to me but not to my more picky self :)

Done. Hope picky @veloman-yunkan is happy with the change.

> Please merge after addressing the two concerns with the commit history

I need a explicit approval to merge. Please approve (and merge directly while you have the button under your mouse cursor)

2024-06-17 13:05 UTC, kelson42 approved these changes
LGTM ;)

2024-06-17 13:05 UTC, merged